### ISSUE TITLE
requests.exceptions.InvalidURL when trying to crawl locally

### ISSUE THREAD

**Issue by lanegoolsby** [typesense/typesense-docsearch-scraper#10]
The string concatenation logic that builds the URL requires the `TYPESENSE_PATH` variable. That is not in the documentation. 

If the variable is not present then the URL gets concatenated to `http://host.docker.internal:8108None/collections/xyz`

The 'None' part of the string is coming from [here](https://github.com/typesense/typesense-docsearch-scraper/blob/a42914158ec485eea45fa4214e1980abc7c09a6a/scraper/src/typesense_helper.py#L20) I think.

**Comment by jasonbosco** [comment]
@lanegoolsby Looks like this was a regression from #9. I've pushed out a fix. Could you do `docker pull typesense/docsearch-scraper` and try again?

**Comment by lanegoolsby** [comment]
Looks good!
