### ISSUE TITLE
Is this actively maintained?

### ISSUE THREAD

**Issue by darknightdev** [typesense/typesense-docsearch-scraper#18]
## Description
As per Docusaurus documentation we are looking to use and host this scrapper. We don't see lot of activity recently in the project and just wanted to make sure if this project is actively maintained. 
Thanks

## Steps to reproduce
None

## Metadata

**Typesense Version**:

**OS**:

**Comment by jasonbosco** [comment]
It most certainly is :)

I should say Algolia has done a fantastic job making their original scraper super robust, so it continues to work well without many changes. And if any issues crop up in this fork, we intend to fix them.
