### ISSUE TITLE
Add docker image for Apple silicon (arm64)?

### ISSUE THREAD

**Issue by PupilTong** [typesense/typesense-docsearch-scraper#19]
## Description

I'm using Apple Silicon Macbook for developing.

I followed the instruction(https://typesense.org/docs/guide/docsearch.html) about creating a self-host server for docusaurus.  However I found that the current docker image, `typesense/docsearch-scraper-base`, does not support apple silicon computer.

## Steps to reproduce

Just follow the instruction to the step 5

`$ docker run -it --env-file=/path/to/your/.env -e "CONFIG=$(cat /path/to/your/config.json | jq -r tostring)" typesense/docsearch-scraper`

it returns a warning on my Macbook

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

## Expected Behavior

supports arm64

## Actual Behavior

using linux64 version ubuntu

## Metadata

**Typesense Version**:

**OS**: Darwin **.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

**Comment by PupilTong** [comment]
I successfully made the `typesense/docsearch-scraper-base` work on my computer by made some minor modification on the original Dockerfile.
https://hub.docker.com/layers/pupiltong/typesense-docsearch-scraper-base/latest/images/sha256-3da0b8b940dfd19072a62080ea52827ec77cdfe8b79f8e34af496d96303d4edc?context=explore
Will create a PR if you guys feel this could help XD

**Comment by jasonbosco** [comment]
A PR would be great! Thank you!

**Comment by jasonbosco** [comment]
This is most likely superseded by #58. But please let me know if it still doesn't work on Apple Silicon with v0.11.0 of the scraper, which now has multi-arch images published to Docker Hub
