### ISSUE TITLE
Support configurable `locale` on creating one collections's fields.

### ISSUE THREAD

**Issue by PupilTong** [typesense/typesense-docsearch-scraper#21]
## Description

Related Issue: https://github.com/typesense/typesense/issues/267

Related Code: https://github.com/typesense/typesense-docsearch-scraper/blob/a005d7a8bbd45bd71fd3895024f05663e9f797c6/scraper/src/typesense_helper.py#L34-L53

The scraper doesn't set the `locale` property on creating fields, which makes chinese words searching doesn't work as expected.

## Steps to reproduce

just run the scraper and typesense docker image 0.23.1

**Comment by stoneqq11** [comment]
i hava the same trubbel

**Comment by Markeli** [comment]
Yeah, me to! I think configuring `locale ` via environment variables would be very simple solution. Similar to providing host, port and rest parameters for typesesne client.

![image](https://user-images.githubusercontent.com/5919274/219793135-6922ccbc-3d37-48fc-931b-ea61a3bd4c1c.png)

@jasonbosco, I can make a PR if you agree with this solution.

**Comment by jasonbosco** [comment]
@Markeli Great idea! I was thinking of a more complicated solution, but yours is much simpler. A PR would be great!

**Comment by Markeli** [comment]
@jasonbosco, I've made a PR.

**Comment by jasonbosco** [comment]
Thanks @Markeli! Just merged it in.

**Comment by Markeli** [comment]
@jasonbosco, could you, please, push new image of scrapper to dockerhub?

**Comment by jasonbosco** [comment]
@Markeli Done.
