### ISSUE TITLE
After rerun docsearch-scraper there is status code 404 on delete previous collection 

### ISSUE THREAD

**Issue by jasiek-net** [typesense/typesense-docsearch-scraper#26]
## Description

When I try to rescrape documentation, I've got error at the end (404).

## Steps to reproduce

Scrape documentation in docusaurus once, then rerun scraper
```
docker run -p 8080:8080 -it --env-file=./.env -e "CONFIG=$(cat ./typesense.json | jq -r tostring)" typesense/docsearch-scraper
```

## Expected Behavior

Replace existing docs with new one.

## Actual Behavior

Error on delete collection

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/seleuser/src/index.py", line 116, in <module>
    run_config(environ['CONFIG'])
  File "/home/seleuser/src/index.py", line 104, in run_config
    typesense_helper.commit_tmp_collection()
  File "/home/seleuser/src/typesense_helper.py", line 90, in commit_tmp_collection
    self.typesense_client.collections[old_collection_name].delete()
  File "/home/seleuser/.local/share/virtualenvs/seleuser-AdYDHarm/lib/python3.10/site-packages/typesense/collection.py", line 22, in delete
    return self.api_call.delete(self._endpoint_path())
  File "/home/seleuser/.local/share/virtualenvs/seleuser-AdYDHarm/lib/python3.10/site-packages/typesense/api_call.py", line 158, in delete
    return self.make_request(requests.delete, endpoint, True,
  File "/home/seleuser/.local/share/virtualenvs/seleuser-AdYDHarm/lib/python3.10/site-packages/typesense/api_call.py", line 115, in make_request
    raise ApiCall.get_exception(r.status_code)(r.status_code, error_message)
typesense.exceptions.ObjectNotFound: [Errno 404] No collection with name `xxx` found.
```

## Metadata

**Typesense Version**: 0.24

**OS**: macbook

**Comment by jasonbosco** [comment]
Looks like the previous collection might have been deleted manually outside of the scraper... 

To fix this, you want to [delete the alias](https://typesense.org/docs/0.24.0/api/collection-alias.html#delete-an-alias) and the [collection](https://typesense.org/docs/0.24.0/api/collections.html#drop-a-collection) created by the scraper via the API, and then then re-run the scraper.

**Comment by nascode** [comment]
@jasonbosco I experience this issue too. 

I am using Typesense cloud, and the scraping process can only be done succesfully when I deleted all collection and alias.

Then next attempt to scrape will always fail (Delete collection not found)

**Comment by jasonbosco** [comment]
@nascode The next time this happens, could you look at the Alias section in your Typesense Cloud dashboard and let me know if the collection that the alias is pointing to exists?

**Comment by nascode** [comment]
@jasonbosco 

Before running the scraper, here are my collection list and alias

<img width="207" alt="image" src="https://github.com/typesense/typesense-docsearch-scraper/assets/1393516/32e753dd-3210-4137-8d5b-46a0be22efcb">
<img width="985" alt="image" src="https://github.com/typesense/typesense-docsearch-scraper/assets/1393516/07a00f28-9df5-49f1-af42-8280f51a7e3b">

Then I tried to run the scraper and got this error

```
typesense.exceptions.ObjectNotFound: [Errno 404] No collection with name `service-bridge-index_1689120603` found.
```

**Comment by jasonbosco** [comment]
Could you show me similar screenshots of the alias screen and the collection selector after you run the scraper?

Also could you double-check that there is only one instance of the scraper running?

**Comment by jasonbosco** [comment]
@timolagus Thank you for those details. I increased the timeout for all write operations in `v0.9.1` of the scraper to solve for a different use-case, but that would definitely help with deletes timing out as well. 

We've also made some improvements to the collection delete performance in `v0.25.2` of Typesense Server, which should also help prevent this issue.
