### ISSUE TITLE
Which versions of typesense-server is docsearch-scraper compatible with?

### ISSUE THREAD

**Issue by Krinkle** [typesense/typesense-docsearch-scraper#34]
## Description

For improved security, I'd like to pin the version of the Docker Hub image `typesense/docsearch-scraper` version and upgrade this from time to time. It is unclear to me at this time which version(s) of the typesense-server a given version of the scraper is compatible with. Is this documented somewhere?

**Comment by jasonbosco** [comment]
Just added a compatibility matrix here: https://github.com/typesense/typesense-docsearch-scraper/blob/master/README.md#compatibility
