### ISSUE TITLE
Roadmap / sustainability of fork

### ISSUE THREAD

**Issue by refset** [typesense/typesense-docsearch-scraper#4]
## Description

Has there been any discussion / decision in regards maintaining this fork beyond Algolia's planned EOL?

From https://docsearch.algolia.com/docs/migrating-from-legacy/#faq
> Are the docsearch-scraper and docsearch-configs repository still maintained?
>
> At the time you are reading this, the migration hasn't been completed, so yes they are still maintained.
> Once the migration has been completed:
> The docsearch-scraper will be archived and not maintained in favor of our Algolia Crawler, you'll still be able to use our run your own solution if you want!

**Comment by jasonbosco** [comment]
@refset Thank you for pointing this out! Didn't realize Algolia is switching from their open source docsearch-scraper to their internal proprietary crawler. 

In any case, happy to maintain this fork of docsearch-scraper that works with Typesense, even beyond Algolia's planned EOL. 

Would definitely appreciate any and all help from the community as needed :)
