### ISSUE TITLE
Provide multi-arch docker image

### ISSUE THREAD

**Issue by darkweaver87** [typesense/typesense-docsearch-scraper#57]
## Description

Scraper is currently not working on ARM architecture for instance.

## Steps to reproduce

Run it on an ARM machine, you will get an `exec format error`.

## Expected Behavior

Run it as it runs on X86.

## Actual Behavior

Doesn't run.
I'll be happy to help on that topic but I didn't find any CI job I can modify which actually produces the docker image ...
I understand that selenium can't be installed on ARM but do you think to some alternatives ?

## Metadata

**Typesense Version**: 0.25.2

**OS**: any OS running containerd/dockerd

**Comment by jasonbosco** [comment]
A PR to make it multi-arch would be great. 

I follow the steps in this section of the README to release a new version: https://github.com/typesense/typesense-docsearch-scraper?tab=readme-ov-file#releasing-a-new-version

**Comment by darkweaver87** [comment]
OK thanks, I wanted to check if there were any kind of CI job for releasing. I'll open a PR then :-)

**Comment by immanuelfodor** [comment]
Fixed by https://github.com/typesense/typesense-docsearch-scraper/pull/58

**Comment by jasonbosco** [comment]
Thank you again @darkweaver87!
