### ISSUE TITLE
multu-arch cut off amd64

### ISSUE THREAD

**Issue by bfg-serge** [typesense/typesense-docsearch-scraper#69]
## Description

It looks like the new release removed support of amd64 platform 
see the list of OS/ARCH here: https://hub.docker.com/r/typesense/docsearch-scraper/tags

## Steps to reproduce

Run the last version on amd64 (EX: github action with latest ubuntu) and get 
```
Status: Downloaded newer image for typesense/docsearch-scraper:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
```

## Expected Behavior

nicely working docsearch-scraper

## Metadata

**Typesense Version**: latest

**OS**: linux

**Comment by jasonbosco** [comment]
Oops, sorry about that. Missed a step in the build process when promoting RC build to GA. 

Just fixed it. Could you try again now after clearing any caches?

**Comment by bfg-serge** [comment]
@jasonbosco you rock! 
thanks all good now!

**Comment by jasonbosco** [comment]
Awesome, thank you for confirming! 🙌
