### ISSUE TITLE
hierarchy_radio should also be flattened like hierarchy

### ISSUE THREAD

**Issue by nascosto** [typesense/typesense-docsearch-scraper#71]
## Description
We want to leverage hierarchy_radio in our queries, but it isn't flattened in the transformer.

## Expected Behavior

hierarchy_radio is available

Updated in https://github.com/typesense/typesense-docsearch-scraper/pull/70

**Comment by jasonbosco** [comment]
Thank you for the PR. Published it in `0.12.0.rc1`. Could you give it a shot and let me know if it works as expected now?

**Comment by nascosto** [comment]
Yes. I should be able to validate later today.

**Comment by nascosto** [comment]
I apologize. I forgot about this issue. It works.
